key = "85bb83e839691e89"
url = "http://api.wunderground.com/api/{}/conditions/q/{},{}.json"

weather_ranks = {
    'Heavy Thunderstorms with Hail' : 1,
    'Light Thunderstorms with Hail' : 2,
    'Heavy Hail Showers' : 3,
    'Light Hail Showers' : 4,
    'Heavy Hail' : 5,
    'Light Hail' : 6,
    'Small Hail' : 7,
    'Heavy Thunderstorms and Ice Pellets' : 8,
    'Light Thunderstorms and Ice Pellets' : 9,
    'Heavy Ice Crystals' : 10,
    'Light Ice Crystals' : 11,
    'Heavy Ice Pellet Showers' : 12,
    'Light Ice Pellet Showers' : 13,
    'Heavy Ice Pellets' : 14,
    'Light Ice Pellets' : 15,
    'Heavy Thunderstorms and Snow' : 16,
    'Light Thunderstorms and Snow' : 17,
    'Heavy Snow Showers' : 18,
    'Light Snow Showers' : 19,
    'Heavy Snow Grains' : 20,
    'Light Snow Grains' : 21,
    'Heavy Snow' : 22,
    'Light Snow' : 23,
    'Heavy Thunderstorms with Small Hail' : 24,
    'Light Thunderstorms with Small Hail' : 25,
    'Heavy Thunderstorm' : 26,
    'Light Thunderstorm' : 27,
    'Heavy Thunderstorms and Rain' : 28,
    'Light Thunderstorms and Rain' : 29,
    'Heavy Rain Showers' : 30,
    'Light Rain Showers' : 31,
    'Heavy Rain' : 32,
    'Light Rain' : 33,
    'Heavy Rain Mist' : 34,
    'Light Rain Mist' : 35,
    'Heavy Drizzle' : 36,
    'Light Drizzle' : 37,
    'Heavy Mist' : 38,
    'Light Mist' : 39,
    'Heavy Fog' : 40,
    'Light Fog' : 41,
    'Overcast' : 42,
    'Mostly Cloudy' :43,
    'Partly Cloudy' : 44,
    'Scattered Clouds' : 45,
    'Clear' : 46
}
